### ISSUE TITLE
expected shape of era5 data?

### ISSUE THREAD

**Issue by mishooax** [tobifinn/ensemble_transformer#6]
hi @tobifinn - nice work, thanks for open sourcing it!

I'm trying to run your code to get a better understanding of how the ensemble attention works. I downloaded TIGGE-IFS (50 ensemble members) and ERA5 reanalysis data for 2017 and ran both through the pre-processing pipeline. Everything seems to work until i run `fit_normalizer.ipynb`. This raises an error:

```
for ifs_data, era_data in tqdm(data_module.train_dataloader(), total=len(data_module.train_dataloader())):
    print(ifs_data.shape)
    print(era_data.shape)
    ifs_mean = ifs_data.mean(dim=(1, 3, 4), keepdim=True).sum(dim=0, keepdim=True)
    ifs_squared_mean = ifs_data.pow(2).mean(dim=(1, 3, 4), keepdim=True).sum(dim=0, keepdim=True)
    era_mean = era_data.mean(dim=(1, 2, 3), keepdim=True).sum(dim=0, keepdim=True)
    era_squared_mean = era_data.pow(2).mean(dim=(1, 2, 3), keepdim=True).sum(dim=0, keepdim=True)
    try:
        rolling_sum['ifs'] = rolling_sum['ifs']+ifs_mean
        rolling_squared_sum['ifs'] = rolling_squared_sum['ifs']+ifs_squared_mean
        rolling_sum['era'] = rolling_sum['era']+era_mean
        rolling_squared_sum['era'] = rolling_squared_sum['era']+era_squared_mean
    except:
        rolling_sum['ifs'] = ifs_mean
        rolling_squared_sum['ifs'] = ifs_squared_mean
        rolling_sum['era'] = era_mean
        rolling_squared_sum['era'] = era_squared_mean
    rolling_elems += ifs_data.shape[0]
```

Output
```
 0%|          | 0/29 [00:00<?, ?it/s]
torch.Size([16, 50, 3, 32, 64])
torch.Size([16, 32, 64])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_20355/3535360696.py in <module>
      4     ifs_mean = ifs_data.mean(dim=(1, 3, 4), keepdim=True).sum(dim=0, keepdim=True)
      5     ifs_squared_mean = ifs_data.pow(2).mean(dim=(1, 3, 4), keepdim=True).sum(dim=0, keepdim=True)
----> 6     era_mean = era_data.mean(dim=(1, 2, 3), keepdim=True).sum(dim=0, keepdim=True)
      7     era_squared_mean = era_data.pow(2).mean(dim=(1, 2, 3), keepdim=True).sum(dim=0, keepdim=True)
      8     try:

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
```

What's the expected shape of the ERA5 `t2m` dataset? Thanks!

**Comment by mishooax** [comment]
hm... looks like adding an extra dummy dimension to the `era_data` tensor gets me rid of the error
```
era_data = era_data[:, np.newaxis, ...]
```

[later edit] but it doesn't get me very far, i get shape error during training

```
$ python ensemble_transformer/scripts/train.py
Global seed set to 42
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type           | Params | In sizes            | Out sizes
---------------------------------------------------------------------------------------------
0 | embedding     | ModelEmbedding | 209 K  | [1, 50, 3, 32, 64]  | [1, 50, 64, 32, 64]
1 | transformers  | Sequential     | 278 K  | [1, 50, 64, 32, 64] | [1, 50, 64, 32, 64]
2 | output_layer  | EnsConv2d      | 65     | [1, 50, 64, 32, 64] | [1, 50, 1, 32, 64]
3 | metrics       | ModuleDict     | 96     | ?                   | ?
4 | loss_function | WeightedScore  | 32     | ?                   | ?
---------------------------------------------------------------------------------------------
488 K     Trainable params
96        Non-trainable params
488 K     Total params
1.954     Total estimated model params size (MB)
Validation sanity check:   0%|                                                                                                                                          | 0/2 [00:00<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "ensemble_transformer/scripts/train.py", line 83, in <module>
    main_train()
  File "lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "ensemble_transformer/scripts/train.py", line 79, in main_train
    trainer.fit(model=network, datamodule=data_module)
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "ensemble_transformer/ens_transformer/models/base_net.py", line 161, in validation_step
    output_ensemble = self(in_tensor)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ensemble_transformer/ens_transformer/models/base_net.py", line 122, in forward
    embedded_tensor = self.embedding(input_tensor)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ensemble_transformer/ens_transformer/layers/model_embedding.py", line 56, in forward
    out_tensor = self.net(in_tensor)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ensemble_transformer/ens_transformer/layers/conv.py", line 39, in forward
    convolved_tensor = self.conv2d(in_tensor)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ensemble_transformer/ens_transformer/layers/ens_wrapper.py", line 34, in forward
    modified_tensor = self.base_layer(in_tensor_batched)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 5, 5], but got 5-dimensional input of size [8, 50, 3, 36, 68] instead
```

Any idea what may be going on here? Thanks!

**Comment by tobifinn** [comment]
Yes, it seems indeed that the "feature" dimension in `era_data` was missing . There is already an existing normalizer included within `data/interim/normalizer.pt` that fitted on the training data 2017/2018, so to reproduce the results you don't have to rerun the normalizer script.

**Comment by tobifinn** [comment]
Which version of the repo are you using? The current main branch or the tagged workshop version? and what are your pytorch and pytorch lightning versions?

**Comment by mishooax** [comment]
I am using the code on the main branch.

``` conda list | grep pytorch
# packages in environment at /data/conda/condaenvs/s2s-pytorch:
pytorch                   1.8.0           cuda102py38h540557e_0    conda-forge
pytorch-gpu               1.8.0           cuda102py38hf05f184_0    conda-forge
pytorch-lightning         1.3.8              pyhd8ed1ab_0    conda-forge
```

**Comment by tobifinn** [comment]
For me the train script from the main branch works flawlessly out of the box.
My current working versions are:
```
# Name                    Version                   Build  Channel
pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-lightning         1.4.5                    pypi_0    pypi
```
Nevertheless, it seems like the `ensemble_wrapper` is not working properly, which should be independent from the version of pytorch, because it is a basic operation.  In your error message I miss the notification of pytorch lightning that the working directory was changed, did you changed something within the script? otherwise try again to run it within the scripts folder.

**Comment by mishooax** [comment]
Yes I suspect it's got to do w/ the `ensemble_wrapper` which should (if I understand it correctly) "merge" the leading two dimensions of the batch input? 

Also - I do get a log message telling me that the working directory's been changed (I removed it from the trace output for brevity)

```
[2021-09-22 08:24:49,117][__main__][INFO] - Changed working directory from models/2021-09-22_08-24-49 to ensemble_transformer
```

**Comment by mishooax** [comment]
Right - so I've just added some logging statements to `EnsembleWrapper.forward()`:
```
    def forward(self, in_tensor: torch.Tensor) -> torch.Tensor:
        logger.warning("self.base_layer: %s", self.base_layer)
        logger.warning("in_tensor.shape: %s", in_tensor.shape)
        in_tensor_batched = ens_to_batch(in_tensor)
        logger.warning("in_tensor_batched.shape: %s", in_tensor_batched.shape)
```
Here's what I'm seeing in the program output:
```
$ python train.py
lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2021-09-22 09:03:41,596][__main__][INFO] - Changed working directory from ensemble_transformer/data/models/2021-09-22_09-03-41 to ensemble_transformer/scripts
Global seed set to 42
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:168: LightningDeprecationWarning: The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5. Access the datamodule through using `self.trainer.datamodule` instead.
  rank_zero_deprecation(
[2021-09-22 09:03:45,498][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:45,500][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 3, 36, 68])
[2021-09-22 09:03:45,527][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 3, 36, 68])
[2021-09-22 09:03:46,989][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:46,990][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:46,990][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,012][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,013][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:47,014][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,031][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,052][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,066][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,073][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,075][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,076][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,082][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,084][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,085][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
lib/python3.8/site-packages/numpy/core/fromnumeric.py:86: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
[2021-09-22 09:03:47,353][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,354][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,361][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,367][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,372][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,378][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,600][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,601][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 3, 36, 68])
[2021-09-22 09:03:47,608][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 3, 36, 68])
[2021-09-22 09:03:47,618][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,622][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:47,628][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,634][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,640][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:47,645][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,651][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,656][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,661][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,666][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,674][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,679][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,687][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,691][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,696][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,703][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,707][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,712][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,731][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,736][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,736][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,823][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,823][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 3, 36, 68])
[2021-09-22 09:03:47,823][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 3, 36, 68])
[2021-09-22 09:03:47,824][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,829][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:47,835][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,835][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:47,840][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:47,840][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:47,840][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,845][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,849][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,850][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,855][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,859][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,859][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:47,863][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,868][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,872][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,876][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,881][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:47,887][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:47,892][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:47,897][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:48,005][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:48,005][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 3, 36, 68])
[2021-09-22 09:03:48,005][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 3, 36, 68])
[2021-09-22 09:03:48,006][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:48,011][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:48,017][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:48,024][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:48,028][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 36, 68])
[2021-09-22 09:03:48,028][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 36, 68])
[2021-09-22 09:03:48,029][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:48,034][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:48,038][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:48,039][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:48,043][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:48,047][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:48,053][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
[2021-09-22 09:03:48,057][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:48,058][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:48,058][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:48,067][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:48,072][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])
[2021-09-22 09:03:48,078][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(64, 1, kernel_size=(1, 1), stride=(1, 1))
[2021-09-22 09:03:48,084][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([1, 50, 64, 32, 64])
[2021-09-22 09:03:48,090][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([50, 64, 32, 64])

  | Name          | Type           | Params | In sizes            | Out sizes
---------------------------------------------------------------------------------------------
0 | embedding     | ModelEmbedding | 209 K  | [1, 50, 3, 32, 64]  | [1, 50, 64, 32, 64]
1 | transformers  | Sequential     | 278 K  | [1, 50, 64, 32, 64] | [1, 50, 64, 32, 64]
2 | output_layer  | EnsConv2d      | 65     | [1, 50, 64, 32, 64] | [1, 50, 1, 32, 64]
3 | metrics       | ModuleDict     | 96     | ?                   | ?
4 | loss_function | WeightedScore  | 32     | ?                   | ?
---------------------------------------------------------------------------------------------
488 K     Trainable params
96        Non-trainable params
488 K     Total params
1.954     Total estimated model params size (MB)
Validation sanity check:   0%|                                                                                                                                          | 0/2 [00:00<?, ?it/s]
[2021-09-22 09:03:48,499][ens_transformer.layers.ens_wrapper][WARNING] - self.base_layer: Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
[2021-09-22 09:03:48,499][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor.shape: torch.Size([8, 1, 50, 3, 36, 68])
[2021-09-22 09:03:48,500][ens_transformer.layers.ens_wrapper][WARNING] - in_tensor_batched.shape: torch.Size([8, 50, 3, 36, 68])
Error executing job with overrides: []
(...)
```

The stack trace is essentially the same as before. Are the in / out sizes consistent with the ones you are getting? I'm puzzled by the `in_tensor.shape: torch.Size([8, 1, 50, 3, 36, 68])` - not quite sure where the length-`1` dimension is coming from.

**Comment by tobifinn** [comment]
Yes this length 1 dimension causes the problems. This might be an artifact from the normalization problem ...
Did you tried it with the normalization within the repo?

**Comment by mishooax** [comment]
Can I ask you what's the shape of your normalized data? Just to do a sanity check against what I have now. Thanks!

> Did you tried it with the normalization within the repo?

Not yet, will get to that a bit later.

**Comment by tobifinn** [comment]
Command: `{k: v.mean.shape for k, v in torch.load('../../data/interim/normalizers.pt').items()}`
Output: `{'ifs': torch.Size([1, 3, 1, 1]), 'era': torch.Size([1, 1, 1])}`

**Comment by mishooax** [comment]
Okay, I'm seeing `{'ifs': torch.Size([1, 1, 3, 1, 1]), 'era': torch.Size([1, 1, 1, 1])}`. Looks like a dimension mismatch, yes...

**Comment by tobifinn** [comment]
Yes this seems to be the cause :+1:

**Comment by mishooax** [comment]
also, related q: is this "folding" of the two leading dimensions (batch_size, ensemble_size) what allows you to use different ensemble sizes for training vs. inference, as you seem to claim in the paper (please correct me if i misunderstood this).

**Comment by tobifinn** [comment]
No, its only on the technical site. With the ensemble you do basically a low-rank approximation to the true covariances, if you decrease the number of ensemble members, you increase the noise within the approximation. You get then spurious correlations between ensemble members. On one hand, this regularizes your network (like in a L2-regularization / ridge regression), on the other hand this can lead to instabilities. I basically show there that an approximation with only 10 members works in my case during training quite fine. If one compares this with results from ensemble-based data assimilation, this is quite surprising. Nevertheless, this might be quite different for more complicated architectures :)
